

[[http]]
name = "example-http"
bind-addr = "172.17.0.2:9096"
output = [
    { name="local1", location = "http://172.17.0.3:8086/write", timeout="5s", buffer-size-mb = 100, max-batch-kb = 50, max-delay-interval = "5s" },
    { name="local2", location = "http://172.17.0.4:8086/write", timeout="5s", buffer-size-mb = 100, max-batch-kb = 50, max-delay-interval = "5s" },

]
